import React, { useState } from 'react';

export default function About() {

    const emailRegex = /^\S+@\S+\.\S+$/;
    return (
      <>
        <Head>
          <title>About Us</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
        </main>
      </>
    )
  }




