import Head from "next/head";
import styles from '../styles/Home.module.css';


export default function About() {
    return (
      <>
        <Head>
          <title>About Us</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <p>
         
We are proud to deliver an education that goes beyond textbooks and classrooms.
Our students gain the technical skills, real-world experience, and problem-solving ability
needed to embrace complexity and lead innovation in a rapidly changing workforce.
Through close collaboration with industry, our network of alumni and partners continue to
achieve global success.
Information Sessions
Information sessions are a simple way to figure out the next step along your career path.
Learn more about the programs that interest you.
Big Info
Big Info is the largest program expo and information session at BCIT. It's your chance to find
out about all our programs - from business, computing, and health to engineering, trades,
and applied sciences.
If you missed our fall event the next Big Info is scheduled to return on February 15, 2023.We are proud to deliver an education that goes beyond textbooks and classrooms.
Our students gain the technical skills, real-world experience, and problem-solving ability
needed to embrace complexity and lead innovation in a rapidly changing workforce.
Through close collaboration with industry, our network of alumni and partners continue to
achieve global success.
Information Sessions
Information sessions are a simple way to figure out the next step along your career path.
Learn more about the programs that interest you.
Big Info
Big Info is the largest program expo and information session at BCIT. It's your chance to find
out about all our programs - from business, computing, and health to engineering, trades,
and applied sciences.
If you missed our fall event the next Big Info is scheduled to return on February 15, 2023.
Campus Tours
Tours run weekdays September to May, on our Burnaby campus. See BCIT in person and get a
taste of campus life.</p>
        </main>
      </>
    )
  }
  